[main]
    cmd = zookd2
    dir = /home/student/
    lxcbr = 0
    port = 8080
    http_svcs = dynamic, static

[auth]
    cmd = /zoobar/auth-server.py
    dir = /home/student
    lxcbr = 6
    port = 8081
    fwrule = -s 10.1.1.4 -j ACCEPT
    fwrule = -j REJECT

[dynamic]
    cmd = zookfs
    dir = /home/student/
    url = /zoobar/index.cgi(/.*)?
    lxcbr = 1
    port = 8082
    fwrule = -s main -j ACCEPT
    fwrule = -j REJECT

[static]
    cmd = zookfs
    dir = /home/student/
    url = /zoobar/((echo|index|layout|login|transfer|users)\.html|media/.*\.(css|jpg))
    lxcbr = 2
    port = 8083
    fwrule = -s main -j ACCEPT
    fwrule = -j REJECT
    
[echo]
    cmd = /zoobar/echo-server.py
    dir = /home/student
    lxcbr = 9
    port = 8084