[main]
    cmd = zookd2
    dir = /home/student/
    lxcbr = 0
    port = 8080
    http_svcs = dynamic, static

[auth]
    cmd = zoobar/auth-server.py
    dir = /home/student
    lxcbr = 6
    port = 8081
    fwrule = -s dynamic -j ACCEPT
    fwrule = -s bank -j ACCEPT
    fwrule = -j REJECT

[bank]
    cmd = zoobar/bank-server.py
    dir = /home/student
    lxcbr = 3
    port = 8081
    fwrule = -s dynamic -j ACCEPT
    fwrule = -s auth -j ACCEPT
    fwrule = -s profile -j ACCEPT
    fwrule = -j REJECT

[profile]
    cmd = zoobar/profile-server.py
    dir = /home/student
    lxcbr = 4
    port = 8081
    fwrule = -s dynamic -j ACCEPT
    fwrule = -s bank -j ACCEPT
    fwrule = -j REJECT
    
[dynamic]
    cmd = zookfs
    dir = /home/student/
    url = /zoobar/index.cgi(/.*)?
    lxcbr = 1
    port = 8081
    fwrule = -s main -j ACCEPT
    fwrule = -s auth -j ACCEPT
    fwrule = -s echo -j ACCEPT
    fwrule = -s bank -j ACCEPT
    fwrule = -s profile -j ACCEPT
    fwrule = -j REJECT

[static]
    cmd = zookfs
    dir = /home/student/
    url = (/zoobar/((echo|index|layout|login|transfer|users)\.html|media/.*\.(css|jpg))|/favicon.ico)
    lxcbr = 2
    port = 8081
    fwrule = -s main -j ACCEPT
    fwrule = -j REJECT
    
[echo]
    cmd = zoobar/echo-server.py
    dir = /home/student
    lxcbr = 9
    port = 8081
    fwrule = -s dynamic -j ACCEPT
    fwrule = -j REJECT